Script started on Fri 06 Nov 2015 08:21:38 PM PST
[kzhen002@hammer rshell]$ bin/rshell
kzhen002@hammer.cs.ucr.edu$ # ls
kzhen002@hammer.cs.ucr.edu$ ls # asdasiopdja
bin  cc	 LICENSE  makefile  mc	README.md  README.MD  sm  src  tests
kzhen002@hammer.cs.ucr.edu$ # exit
kzhen002@hammer.cs.ucr.edu$ ls ; # pwd || ps
bin  cc	 LICENSE  makefile  mc	README.md  README.MD  sm  src  tests
kzhen002@hammer.cs.ucr.edu$ ps # # # # #
  PID TTY	   TIME CMD
21986 pts/14   00:00:00 bash
22006 pts/14   00:00:00 rshell
22073 pts/14   00:00:00 ps
kzhen002@hammer.cs.ucr.edu$ ls # ps # pwd # ;
bin  cc	 LICENSE  makefile  mc	README.md  README.MD  sm  src  tests
kzhen002@hammer.cs.ucr.edu$ exit
[kzhen002@hammer rshell]$ exit
exit

Script done on Fri 06 Nov 2015 08:22:40 PM PST
